apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-model-a
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: demo-model-a
  template:
    metadata:
      labels:
        app: demo-model-a
    spec:
      serviceAccountName: my-service-account
      containers:
        - name: demo-model-a
          image: # Docker Image URL
          imagePullPolicy: Always
          ports:
            - containerPort: 8000

